gif_config:
  gifs:
    - name: 'dark'
      theme: 'monokai'

    - name: 'light'
      theme: 'solarized_light'

scenario:
  - expect: "apple\n"
  - write: s

  - expect: "apple\n"
  - write: simba
