terminal_config:
  cols: 77
  rows: 12

interaction_config:
  action_delay: 200
  keystroke_delay: 75

gif_config:
  common:
    font_size: 32
    font_family: JetBrains Mono

  gifs:
    - name: 'safe_user_input_dark'
      theme: 'jetbrains_dark'

    - name: 'safe_user_input'
      theme: 'jetbrains_light'

scenario:
  - expect: \n
  - write: BB

  - expect: \n
  - write: BBYB

  - expect: \n
  - write: BBBB
