gif_config:
  gifs:
    - name: 'dark'
      theme: 'monokai'

    - name: 'light'
      theme: 'solarized_light'

scenario:
  - expect: ".\n"
  - write: b

  - expect: "'squared'\n"
  - write: borderss

  - expect: "'squared'\n"
  - write: borders
