terminal_config:
  cols: 49
  rows: 7

gif_config:
  common:
    font_size: 32
    font_family: JetBrains Mono

  gifs:
    - name: 'choose_filter_dark'
      theme: 'jetbrains_dark'

    - name: 'choose_filter'
      theme: 'jetbrains_light'

scenario:
  - expect: \n
  - wait: 500
  - write: b

  - expect: \n
  - wait: 500
  - write: borderss

  - expect: \n
  - wait: 500
  - write: borders
